### ISSUE TITLE
Images in Documentation. 

### ISSUE THREAD

**Issue by Karna98** [cdli-gh/cdli-gh.github.io#3]
.md File Link: https://github.com/cdli-gh/cdli-gh.github.io/blob/master/_pages/cdli_two_factor_guide.md

Website Page: https://cdli-gh.github.io/guides/cdli_two_factor_guide.html

Website is not able to display images for Two Factor Guide.

@epageperron

**Comment by epageperron** [comment]
![Screenshot_20200625-181455](https://user-images.githubusercontent.com/14226547/85800942-ddb15400-b70f-11ea-8133-726b0d5d8862.png)
